### ISSUE TITLE
Wrong year and missing days

### ISSUE THREAD

**Issue by marc2332** [seniorglez/Advent-of-Code#1]
Hello, I would like to notify you have been doing the wrong advent of code, we are in year 2020 not 2015. You have also some missing days, to be exactly, from day 3 to day 12.

Have a great day 👍🏻

**Comment by seniorglez** [comment]
Every day I want to have you next to me, When you’re not here, I’m always sad, When you are here, my heart is full of joy, I never want to lose you. I deeply appreciate these words of wisdom that you are giving me

**Comment by marc2332** [comment]
😂😂😂😂😂

**Comment by Saul-BT** [comment]
Loneliness be like...
:sob:
